# Generated by Django 6.0.8 on 2026-08-13 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Analysis'), ('PSYCHOLOGICAL', 'Psychological Analysis'), ('NUTRITION', 'Nutrition & Diet'), ('FITNESS', 'Fitness & Conditioning'), ('GENERAL', 'General Insights')], default='TECHNICAL', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='e.g., https://www.youtube.com/embed/...')),
                ('content', models.TextField(help_text='Detailed analysis and notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_modules', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_modules', to='sports.sport')),
            ],
        ),
    ]
