# Generated by Django 6.0.8 on 2026-08-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_link_or_address',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='max_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='meeting_link_or_address',
            field=models.CharField(blank=True, help_text='Physical address or custom link', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_record', to='bookings.availabilityslot'),
        ),
    ]
