# Generated by Django 6.0.8 on 2026-08-16 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.DecimalField(decimal_places=1, help_text='Hours of sleep last night', max_digits=4)),
                ('fatigue_level', models.IntegerField(help_text='1 (Very Fresh) to 10 (Exhausted)')),
                ('training_duration_mins', models.IntegerField(default=0, help_text='Total minutes of training today')),
                ('perceived_exertion', models.IntegerField(default=0, help_text='RPE from 1 (Very Light) to 10 (Max Effort)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
