# Generated by Django 6.0.8 on 2026-08-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='diet_quality',
            field=models.IntegerField(default=5, help_text='1 (Poor) to 10 (Excellent)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='hydration_liters',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Liters of water consumed', max_digits=4),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='muscle_soreness',
            field=models.IntegerField(default=1, help_text='1 (None) to 10 (Extreme)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='resting_heart_rate',
            field=models.IntegerField(blank=True, help_text='Resting Heart Rate in BPM', null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='stress_level',
            field=models.IntegerField(default=1, help_text='1 (Very Low) to 10 (Very High)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in KG', max_digits=5, null=True),
        ),
    ]
