# Generated by Django 6.0.8 on 2026-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard rate per session in INR', max_digits=8),
        ),
    ]
